[site]
title = "你好，耳先生"
subtitle = ""
description = "先生贵姓？耳东陈。好的，这边请，耳先生。"
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "rubble"
domain = "https://www.kilerd.me"
domain_root = ""
default_template = "article.html"

[[statics]]
from = "CNAME"
to = "CNAME"

[[statics]]
from = "ads.txt"
to = "ads.txt"

[extra]
ga = """
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-68997851-1"></script> <script>   window.dataLayer = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag('js', new Date());    gtag('config', 'UA-68997851-1'); </script>
"""