[site]
title = "你好，耳先生"
subtitle = ""
description = "先生贵姓？耳东陈。好的，这边请，耳先生。"
keywords = []
author = ""
email = ""
utc_offset = 800
theme = "rubble"

[url]
url = "https://www.kilerd.me"
root = "/"

[pagination]
page_size = 10

[[pages]]
show_in_nav = true
nav_title = "PORTFOLIOS"
file = "portfolios.md"
template = "page.html"

[[pages]]
show_in_nav = true
nav_title = "我的阅读"
file = "read.md"
template = "page.html"

[[pages]]
show_in_nav = true
nav_title = "ABOUTME"
file = "about.md"
template = "page.html"

[[statics]]
from = "CNAME"
to = "CNAME"

[rss]
enable = true
article_limited = 10

[extra]
ga = """
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-68997851-1"></script> <script>   window.dataLayer = window.dataLayer || [];   function gtag(){dataLayer.push(arguments);}   gtag('js', new Date());    gtag('config', 'UA-68997851-1'); </script>
"""