name: Build blog github page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "Kilerd/staple"
        version: "latest"
        file: "staple-ubuntu.tar.gz"
    - name: Install Staple
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        tar -xvf staple-ubuntu.tar.gz -C $GITHUB_WORKSPACE/bin
        chmod 777 $GITHUB_WORKSPACE/bin/staple
    - name: Build blog
      run: $GITHUB_WORKSPACE/bin/staple build
    - name: Deploy site to gh-pages branch
      uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
      with:
        site-directory: public
        repo-token: ${{ secrets.GH_PAT }}
