name: Build blog github page

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v1
    - uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "Kilerd/staple"
        version: "latest"
        file: "staple-ubuntu.tar.gz"
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Staple
      run: |
        mkdir -p $GITHUB_WORKSPACE/bin
        tar -xvf staple-ubuntu.tar.gz -C $GITHUB_WORKSPACE/bin
        chmod 777 $GITHUB_WORKSPACE/bin/staple
    - name: Build blog
      run: $GITHUB_WORKSPACE/bin/staple build
    - uses: actions/upload-pages-artifact@v3
      with:
        name: "github-pages"
        path: public
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
      with:
        token: ${{ github.token }}
